# Numpy
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.

# Functions and Methods Overview

Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines for the full list.

# Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like
# Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
# Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
# Questions
all, any, nonzero, where
# Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort
# Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
# Basic Statistics
cov, mean, std, var
# Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot

In [82]:
import numpy as np

In [83]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [84]:
a.shape #the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.

(3L, 5L)

In [85]:
a.ndim #the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

2

In [86]:
a.dtype.name #an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

'int32'

In [87]:
a.itemsize #the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

4

In [88]:
a.size #the total number of elements of the array. This is equal to the product of the elements of shape.

15

In [89]:
type(a)

numpy.ndarray

In [90]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

# Arrays

NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

# ndarray.ndim
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.
# ndarray.shape
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.
# ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape.
# ndarray.dtype
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
# ndarray.itemsize
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
# ndarray.data
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [93]:
a = np.array([2,3,4])
print a
a.dtype

[2 3 4]


dtype('int32')

In [96]:
b = np.array([(1.5,2,3), (4,5,6)])
b.dtype

dtype('float64')

In [97]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c.dtype

dtype('complex128')

In [98]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [99]:
np.ones( (2,3,4), dtype=np.int16 )  # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [103]:
np.empty((2,3)) # uninitialized, output may vary

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [104]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [105]:
np.arange( 0, 2, 0.3 ) 

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [106]:
from numpy import pi
np.linspace( 0, 2, 9 ) # 9 numbers from 0 to 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

# Array Indexing

In [110]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [111]:
a[2]

8

In [112]:
a[2:5]

array([ 8, 27, 64])

In [113]:
a[:6:2]

array([ 0,  8, 64])

In [114]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [115]:
a[ : :-1] 

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

# Basic Operations

In [118]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [119]:
c = a-b
c

array([20, 29, 38, 47])

In [120]:
b**2

array([0, 1, 4, 9])

In [121]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [122]:
a<30

array([ True, False, False, False], dtype=bool)

In [128]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
b

array([[ 0.99875974,  0.29433442,  0.18200752],
       [ 0.69584854,  0.65011481,  0.73836123]])

In [132]:
b.sum()

3.5594262604413838

In [135]:
b.min()

0.18200752196385606

In [136]:
b.max()

0.99875974038430237

In [140]:
b.sum(axis=0) # sum of each column

array([ 1.69460828,  0.94444923,  0.92036875])

In [141]:
b.sum(axis=1)  # sum of each row

array([ 1.47510169,  2.08432458])

In [139]:
b.cumsum(axis=1) # cumulative sum along each row

array([[ 0.99875974,  1.29309416,  1.47510169],
       [ 0.69584854,  1.34596335,  2.08432458]])

In [142]:
np.sqrt(b)

array([[ 0.99937968,  0.54252597,  0.4266234 ],
       [ 0.83417537,  0.80629697,  0.85927948]])

In [143]:
np.exp(b)

array([[ 2.71491254,  1.3422327 ,  1.19962322],
       [ 2.00541002,  1.91576076,  2.09250356]])

In [145]:
b

array([[ 0.99875974,  0.29433442,  0.18200752],
       [ 0.69584854,  0.65011481,  0.73836123]])

In [146]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [147]:
np.add(b,a)

array([[ 1.99875974,  1.29433442,  1.18200752],
       [ 1.69584854,  1.65011481,  1.73836123]])

In [148]:
b

array([[ 0.99875974,  0.29433442,  0.18200752],
       [ 0.69584854,  0.65011481,  0.73836123]])

In [149]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [150]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

In [151]:
A*B # elementwise product

array([[2, 0],
       [0, 4]])

In [154]:
A.dot(B) # matrix product

array([[5, 4],
       [3, 4]])

In [155]:
np.dot(A, B) # another matrix product

array([[5, 4],
       [3, 4]])

# Multidimensional Arrays

In [156]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [157]:
b[2,3]

23

In [158]:
b[0:5, 1]  # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [159]:
 b[ : ,1] # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [160]:
b[1:3, : ] # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [161]:
b[-1]  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [163]:
c = np.array( [[[  0,  1,  2], [ 10, 12, 13]],[[100,101,102],[110,112,113]]])  # a 3D array (two stacked 2D arrays)
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [164]:
c.shape

(2L, 2L, 3L)

# Iterating

In [167]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [168]:
for row in b:
    print row

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [169]:
for element in b.flat:
    print element

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Shape Manipulating

In [170]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 4.,  6.,  3.,  3.],
       [ 0.,  6.,  4.,  7.],
       [ 6.,  4.,  9.,  5.]])

In [172]:
a.shape

(3L, 4L)

In [173]:
 a.ravel()  # returns the array, flattened

array([ 4.,  6.,  3.,  3.,  0.,  6.,  4.,  7.,  6.,  4.,  9.,  5.])

In [174]:
a.reshape(6,2)  # returns the array with a modified shape

array([[ 4.,  6.],
       [ 3.,  3.],
       [ 0.,  6.],
       [ 4.,  7.],
       [ 6.,  4.],
       [ 9.,  5.]])

In [175]:
a.T  # returns the array, transposed

array([[ 4.,  0.,  6.],
       [ 6.,  6.,  4.],
       [ 3.,  4.,  9.],
       [ 3.,  7.,  5.]])

In [176]:
a.T.shape

(4L, 3L)

In [177]:
a.shape

(3L, 4L)

# Broadcasting rules

Broadcasting allows universal functions to deal in a meaningful way with inputs that do not have exactly the same shape.

The first rule of broadcasting is that if all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.

After application of the broadcasting rules, the sizes of all arrays must match. More details can be found in Broadcasting.